// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-3BujcGEm55Zo9pooeHWDVfoF0Y3oA8',
    appId: '1:639479435926:web:7192e42d2de050f4ec68b7',
    messagingSenderId: '639479435926',
    projectId: 'flip-66d56',
    authDomain: 'flip-66d56.firebaseapp.com',
    databaseURL: 'https://flip-66d56-default-rtdb.firebaseio.com',
    storageBucket: 'flip-66d56.firebasestorage.app',
    measurementId: 'G-3TTKT1D0Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5tAsIjQRa35tvMqdhyOEBO-pZoRxC5Mg',
    appId: '1:639479435926:android:a3fa04adf461b570ec68b7',
    messagingSenderId: '639479435926',
    projectId: 'flip-66d56',
    databaseURL: 'https://flip-66d56-default-rtdb.firebaseio.com',
    storageBucket: 'flip-66d56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwsJ_3Iqw93jfHy_JiUdmQF2GR4Zq9_8',
    appId: '1:639479435926:ios:c450775bd0cb7322ec68b7',
    messagingSenderId: '639479435926',
    projectId: 'flip-66d56',
    storageBucket: 'flip-66d56.firebasestorage.app',
    iosBundleId: 'com.example.flip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-3BujcGEm55Zo9pooeHWDVfoF0Y3oA8',
    appId: '1:639479435926:web:adc2704bc23e91deec68b7',
    messagingSenderId: '639479435926',
    projectId: 'flip-66d56',
    authDomain: 'flip-66d56.firebaseapp.com',
    databaseURL: 'https://flip-66d56-default-rtdb.firebaseio.com',
    storageBucket: 'flip-66d56.firebasestorage.app',
    measurementId: 'G-6N4RBRKGBT',
  );

}